project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning para Data Scientist"
  navbar:
    left:
      - href: index.qmd
        text: Grau en Estadística
      # - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



